### ISSUE TITLE
question: does it support half-width font?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/CircusEditor#1]
i have da capo 3 x-rated japanese release, and i have not try it yet, 
but does it support half-width font (english)?
and will this support another circus based games as well, e.g fortissimo exa/exs?

here is why i'm asking this,
as we know that mangagamer release the da capo 3 with unity engine, and they using bgi/ethornell for da capo 1 & 2...
why are they doing that?
probably, they aware that adv32 doesnt support half-width font...
why i know this, because i already tried with fortissimo exa, unless it use full-width font, it wont load...

**Comment by marcussacana** [comment]
I think he change the engine because the space is a problem sometimes...
in the circus all string bytes have 0x20 decremented, and the " " (yes, space) is exactally 0x20,
And now, with the encryption 0x20-0x20=0x00.... And 0x00 = String End "Flag", so isn't possible put space in some builds of this engine, others builds have the $ replaced to space when run...
I think this is the reason to change the engine.
About the half-width... is shift-jis... SJIS contains by default half-width chars... or are you talking about the monospaced font?

**Comment by 0xh3LL0** [comment]
maybe something like that,
here is the example i did with fortissimo exa,
when i type "ABCDEFGH" with half-width font, it appear as "A C E G", yes with the "space" between them, and the B, D, F, H are missing?
does this problem appear as well on da capo 3? or is it not?

**Comment by marcussacana** [comment]
I don't have the Da capo 3 here, but with D.S works fine.
![https://cdn.discordapp.com/attachments/322612226110259202/342550351297249280/whpraz.png](https://cdn.discordapp.com/attachments/322612226110259202/342550351297249280/whpraz.png)
Try launch the game with this executable
[DSAO.zip](https://github.com/marcussacana/CircusEditor/files/1313297/DSAO.zip)

**Comment by 0xh3LL0** [comment]
thats great! but too bad that i cant play any game at the moment cause my drive is broken, and [i'm on the way to recover it...](https://i.imgur.com/RqmIZ0e.png)
however, here is both fortissimo [script](https://drive.google.com/file/d/0B4E8zrOX6ZdWNktUNlBuMmFuV00/view?usp=sharing), will you take a look at it?

**Comment by marcussacana** [comment]
I think the script will not help, maybe is needed modify the game executable, if you have lucky maybe other game executable can run this game? like that dsao i upload in the comment above...

Test and say-me the results after...

**Comment by 0xh3LL0** [comment]
okay, i'll get the result tomorrow...
thanks!

**Comment by 0xh3LL0** [comment]
okay, here is it...
circuseditor did nothing when i load the MES file
https://i.imgur.com/YfPXvIf.png

and this one is my test with [fortissimo_exa_text](http://www.mediafire.com/file/2uysad3b23qzxag/fortissimo_exa_text.rar) (which is not compatible with da capo 3)
at the first line, the text is typed in full-width, resulting bigger text, and took much place, also the text is cutted (unless i put the line-breaks)
and the second line, i put the same text as above in a half-width (english), but as you can see, it just appear as "T E" the "H" and the rest of the text is missing...
https://i.imgur.com/Kt9jWD3.png

i have tried with your attached dalsegno exe, but it did nothing...

btw, this is the directory structure, same as circus games, right?
https://i.imgur.com/OXDTa0v.png

**Comment by marcussacana** [comment]
Okay, i have added initial support to both games, he can miss some dialogs, if you found any line missing, write to me the line (i don't know japanese) and i will try give a look.

About the problem with ascii letters, maybe you need a hack in your team to modify the engine.

**Comment by 0xh3LL0** [comment]
okay, here is it...
the MES is editable now
https://i.imgur.com/WMcEnxV.png
but this problem is remain, some text still missing...
https://i.imgur.com/nliTbgl.png

**Comment by marcussacana** [comment]
Test this line:｛ ／The quick brown fox jumps over the lazy dog｝

**Comment by 0xh3LL0** [comment]
here is the result...

{ /THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG} 
or { ／THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG}
https://i.imgur.com/tHf4F5r.png

{ /the quick brown fox jumps over the lazy dog}
or { ／the quick brown fox jumps over the lazy dog}
https://i.imgur.com/OCxOBcT.png

**Comment by marcussacana** [comment]
Looks the engine really don't support non-monospaced fonts... 
Without download the game i can't have sure of what is the problem, srry...

**Comment by 0xh3LL0** [comment]
nope, its okay, 
maybe the newer adv32 engine updated with english font support (like in the dal segno does),
btw, thanks for your time,
i'll close it anyway...
